---
name: tests

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      BRANCH_NAME:
        type: string
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.BRANCH_NAME }}
      - name: Run JS Unit
        run: echo "TESTS RUN"

